#version: '3.8'

services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    network_mode: "host"
    env_file:
      - .env
