#version: '3.8' // Because docker 2.0 doesn't work with 3.8
# environment variable have been moved to the .env file

services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    network_mode: "host"
    extra_hosts:
      - "isc-coordinator.lan:192.168.88.250"
    env_file:
      - .env
