version: '3.8'

services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    network_mode: "host"
    environment:
      - XMPP_JID=client@isc-coordinator.lan
      - XMPP_PASSWORD=plsnohack 
      - ROBOT_RECIPIENT=alpha-pi-zero-agent@prosody
      - ROBOT_INSTRUCTIONS=forward,backward,left,right,stop
